### ISSUE TITLE
Project Day 1

### ISSUE THREAD

**Issue by Niranjan2054** [Niranjan2054/magazine#1]
Keep the **link of your project repository**, with the final commit message "**Day 1 project completed**" along with your **FULL NAME** and **COLLEGE ROLL NUMBER.**.

**Comment by shakyaninja** [comment]
https://github.com/shakyaninja/magazine/tree/tech
LUJA SHAKYA KCE074BCT022

**Comment by Amitduwal11** [comment]
https://github.com/Amitduwal11/magazine
Amit Duwal
KCE075BCT006

**Comment by JuJu2181** [comment]
https://github.com/JuJu2181/magazine
Anish Shilpakar
KCE075BCT008

**Comment by Niranjan2054** [comment]
> https://github.com/shakyaninja/magazine/tree/tech
> LUJA SHAKYA KCE074BCT022

Change your project structure.... 
Project ko structure milaunu holla hai jasari class ma banako theyau testai structure milaunu holla

**Comment by Niranjan2054** [comment]
> https://github.com/Amitduwal11/magazine
> Amit Duwal
> KCE075BCT006



> https://github.com/JuJu2181/magazine
> Anish Shilpakar
> KCE075BCT008

Both of you
Assets root directory bhitra rakheko xa 
root directory bhitra ko assets hamro front end ko lagi use garxau cms bhitra nai arko assets folder create garera tyaha chai rakhnu holla cms ko assets

**Comment by Niranjan2054** [comment]
> https://github.com/JuJu2181/magazine
> Anish Shilpakar
> KCE075BCT008

Timro ma config folder bhitra error xa 
check hai init ko last line include hudaina check it hai 

ani redirect garne bela without message pani redirect garna milne gari default value rakhnu

**Comment by Amitduwal11** [comment]
https://github.com/Amitduwal11/magazine
Amit Duwal
KCE075BCT006

**Comment by roobeen-b** [comment]
https://github.com/roobeen-b/magazine
Rubin Baidhya
KCE075BCT034

**Comment by Niranjan2054** [comment]
> https://github.com/Amitduwal11/magazine
> Amit Duwal
> KCE075BCT006

**Checked**

**Comment by Niranjan2054** [comment]
> https://github.com/roobeen-b/magazine
> Rubin Baidhya
> KCE075BCT034

**Checked**

**Comment by dipesjoshi** [comment]
2e9778d4ab1cb3a60a01465624687909ddea78a6
Dipesh Joshi
KCE075BCT015

**Comment by JuJu2181** [comment]
https://github.com/JuJu2181/magazine
Anish Shilpakar
KCE075BCT008

**Comment by dipesjoshi** [comment]
daf7798efa3aabff18d8c7bde7a0b5b4a0d8d79c

**Comment by banmala** [comment]
https://github.com/banmala/magazine/

Sunil Banmala
KCE074BCT045

**Comment by rravii** [comment]
https://github.com/rravii/magazine

Ravi Pandit
KCE075BCT028

**Comment by Kitarpshakya** [comment]
https://github.com/Kitarpshakya/magazine/commit/04c7127a76ab4cc7f733a4f3e3fc347384db64b3
pratik shakya 
Kce075Bct024

**Comment by rohitjoey** [comment]
https://github.com/rohitjoey/project_magazine
Rohit Prajapati
074BCT033

**Comment by Manjil-Karki** [comment]
https://github.com/Manjil-Karki/php_web_backend

updated errors

Manjil karki(KCE075BCT019)

**Comment by Niranjan2054** [comment]
> https://github.com/JuJu2181/magazine
> Anish Shilpakar
> KCE075BCT008

**checked**

**Comment by sahasprajapati** [comment]
https://github.com/B10prajapati/magazine/tree/0fd8b650993a79e811a355854184f7f26557e89f

Sahas Prajapati
KCE074BCT037

**Comment by Niranjan2054** [comment]
> https://github.com/banmala/magazine/
> 
> Sunil Banmala
> KCE074BCT045

**Checked**

**Comment by Niranjan2054** [comment]
> https://github.com/rravii/magazine
> 
> Ravi Pandit
> KCE075BCT028

**Checked**

**Comment by Kitarpshakya** [comment]
https://github.com/Kitarpshakya/magazine/commit/0b22fcca43576e4a0ce8e91f0498b697573b4e51
pratik shakya
kce075bct024
server error solved

**Comment by jagritparajuli** [comment]
https://github.com/jagritparajuli/magazine

**Comment by sudips413** [comment]
https://github.com/sudips413/magazine
sudip shrestha(075BCT046)

**Comment by dpesjoc29** [comment]
https://github.com/dipesjoshi/magazine
Dipesh Joshi
KCE075BCT015

**Comment by romanshilpakar** [comment]
https://github.com/romanshilpakar/magazine

ROMAN SHILPAKAR
KCE075BCT031

**Comment by Niranjan2054** [comment]
> [Kitarpshakya/magazine@04c7127](https://github.com/Kitarpshakya/magazine/commit/04c7127a76ab4cc7f733a4f3e3fc347384db64b3)
> pratik shakya
> Kce075Bct024

Check your .htaccess file there is error in line no 4 and 7 
keep your assets file inside cms folder
**Checked**

**Comment by Niranjan2054** [comment]
> https://github.com/jagritparajuli/magazine

class ma bhaneko error check gara in config folder

**Checked**

**Comment by Niranjan2054** [comment]
> https://github.com/sudips413/magazine
> sudip shrestha(075BCT046)

Create .htaccess file 

**checked**

**Comment by Niranjan2054** [comment]
> https://github.com/dipesjoshi/magazine
> Dipesh Joshi
> KCE075BCT015

error in line no 22 in functions.php 
check init function there is an error
keep your assets inside cms folder

**Checked**

**Comment by Niranjan2054** [comment]
> https://github.com/romanshilpakar/magazine
> 
> ROMAN SHILPAKAR
> KCE075BCT031

Create config folder and ,
Keep your config, function and init in config folder 

.htaccess ko extension .txt hunna just .htaccess

login.php 2 thau ma bhayo remove at root directory

**checked**

**Comment by Niranjan2054** [comment]
> https://github.com/rohitjoey/project_magazine
> Rohit Prajapati
> 074BCT033


**Checked**

**Comment by Niranjan2054** [comment]
> https://github.com/Manjil-Karki/php_web_backend
> 
> updated errors
> 
> Manjil karki(KCE075BCT019)

**Checked**

**Comment by Niranjan2054** [comment]
> https://github.com/B10prajapati/magazine/tree/0fd8b650993a79e811a355854184f7f26557e89f
> 
> Sahas Prajapati
> KCE074BCT037

needed to start buffer in index.php

cms bhitra assets ma rakhdeu 

**checked**

**Comment by Nee2z** [comment]
https://github.com/neetuphaiju/magazine.git

Name : Neetu Phaiju
CRN   : 740324

**Comment by ManandharSudip4** [comment]
https://github.com/ManandharSudip4/-magazine

Sudip Manandhar
KCE075BCT045

**Comment by Niranjan2054** [comment]
> https://github.com/neetuphaiju/magazine.git
> 
> Name : Neetu Phaiju
> CRN : 740324

.htaccess file missing

**Checked**

**Comment by Niranjan2054** [comment]
> https://github.com/ManandharSudip4/-magazine
> 
> Sudip Manandhar
> KCE075BCT045

**Checked**
