### ISSUE TITLE
Project Data Base Module

### ISSUE THREAD

**Issue by Niranjan2054** [Niranjan2054/magazine#2]
Keep the **link of your project repository**, with the final commit message **_"Database Module for Project"_** along with your **FULL NAME** and **COLLEGE ROLL NUMBER.**

**Comment by ManandharSudip4** [comment]
https://github.com/ManandharSudip4/-magazine/commits/master
Sudip Manandhar
CRN : KCE075BCT045

**Comment by Niranjan2054** [comment]
> https://github.com/ManandharSudip4/-magazine/commits/master
> Sudip Manandhar
> CRN : KCE0756BCT045

**Checked**

**Comment by JuJu2181** [comment]
https://github.com/JuJu2181/magazine/commit/master
Anish Shilpakar
CRN : KCE075BCT008

**Comment by JuJu2181** [comment]
https://github.com/JuJu2181/magazine/commits/master
Anish Shilpakar
CRN : KCE075BCT008

**Comment by Niranjan2054** [comment]
> https://github.com/JuJu2181/magazine/commits/master
> Anish Shilpakar
> CRN : KCE075BCT008

**Checked**

**Comment by Amitduwal11** [comment]
https://github.com/Amitduwal11/magazine
Amit Duwal
KCE075BCT006

**Comment by roobeen-b** [comment]
https://github.com/roobeen-b/magazine
Rubin Baidhya
KCE075BCT034

**Comment by Manjil-Karki** [comment]
https://github.com/Manjil-Karki/php_web_backend

Manjil karki
(KCE075BCT019)

**Comment by rravii** [comment]
https://github.com/rravii/magazine/commits/master

Ravi Pandit
(KCE075BCT028)

**Comment by jagritparajuli** [comment]
https://github.com/jagritparajuli/magazine
Jagrit Parajuli
076BEL016

**Comment by romanshilpakar** [comment]
https://github.com/romanshilpakar/magazine
ROMAN SHILPAKAR
KCE075BCT031

**Comment by rohitjoey** [comment]
https://github.com/rohitjoey/project_magazine
Rohit Prajapati
074BCT033

**Comment by manandhar01** [comment]
https://github.com/manandhar01/Magazine
Bibek Manandhar
075BCT013

**Comment by dpesjoc29** [comment]
https://github.com/dipesjoshi/magazine/commits/master
Dipesh Joshi
KCE075BCT015

**Comment by Nee2z** [comment]
https://github.com/neetuphaiju/magazine.git

Name : Neetu Phaiju
CRN   : 740324

**Comment by Kitarpshakya** [comment]
https://github.com/Kitarpshakya/magazine/commit/201fffb17faf7a3d6886adc1c5d00b212366c766
Pratik Shakya
KCE075BCT024

**Comment by Niranjan2054** [comment]
> https://github.com/Amitduwal11/magazine
> Amit Duwal
> KCE075BCT006



> https://github.com/roobeen-b/magazine
> Rubin Baidhya
> KCE075BCT034



> https://github.com/Manjil-Karki/php_web_backend
> 
> Manjil karki
> (KCE075BCT019)



> https://github.com/rravii/magazine/commits/master
> 
> Ravi Pandit
> (KCE075BCT028)



> https://github.com/jagritparajuli/magazine
> Jagrit Parajuli
> 076BEL016



> https://github.com/romanshilpakar/magazine
> ROMAN SHILPAKAR
> KCE075BCT031



> https://github.com/rohitjoey/project_magazine
> Rohit Prajapati
> 074BCT033



> https://github.com/manandhar01/Magazine
> Bibek Manandhar
> 075BCT013



> https://github.com/dipesjoshi/magazine/commits/master
> Dipesh Joshi
> KCE075BCT015



> https://github.com/neetuphaiju/magazine.git
> 
> Name : Neetu Phaiju
> CRN : 740324



> [Kitarpshakya/magazine@201fffb](https://github.com/Kitarpshakya/magazine/commit/201fffb17faf7a3d6886adc1c5d00b212366c766)
> Pratik Shakya
> KCE075BCT024

**All Checked**
