### ISSUE TITLE
Login System using Session and Cookie

### ISSUE THREAD

**Issue by Niranjan2054** [Niranjan2054/magazine#3]
Keep the **link of your project repository**, with the final commit message **"Login System using Session and Cookie"** along with your **FULL NAME** and **COLLEGE ROLL NUMBER..**
**_Dateline: May 25 10:00pm_**

**Comment by Nirumishra** [comment]
[magazine-master.zip](https://github.com/Niranjan2054/magazine/files/4673694/magazine-master.zip)

**Comment by ManandharSudip4** [comment]
https://github.com/ManandharSudip4/-magazine
Sudip Manandhar
(KCE075BCT045)

**Comment by banmala** [comment]
https://github.com/banmala/magazine/
Sunil Banmala
KCE074BCT045

**Comment by Nee2z** [comment]
https://github.com/neetuphaiju/magazine.git

Name : Neetu Phaiju
CRN   : 740324

**Comment by JuJu2181** [comment]
https://github.com/JuJu2181/magazine
Anish Shilpakar
CRN : KCE075BCT008

**Comment by Manjil-Karki** [comment]
https://github.com/Manjil-Karki/php_web_backend

MANJIL KARKI
[KCE075BCT019]

**Comment by Amitduwal11** [comment]
https://github.com/Amitduwal11/magazine
Amit Duwal
KCE075BCT006

**Comment by Amitduwal11** [comment]
https://github.com/Amitduwal11/magazine
Amit Duwal
KCE075BCT006

**Comment by manandhar01** [comment]
https://github.com/manandhar01/Magazine
Bibek Manandhar
KCE075BCT013

**Comment by rravii** [comment]
https://github.com/rravii/magazine/commits/master

Ravi Pandit
KCE075BCT028

**Comment by roobeen-b** [comment]
https://github.com/roobeen-b/magazine
Rubin Baidhya
KCE075BCT034

**Comment by romanshilpakar** [comment]
https://github.com/romanshilpakar/magazine

ROMAN SHILPAKAR
KCE075BCT031

**Comment by shakyaninja** [comment]
https://github.com/shakyaninja/WebMag
LUJA SHAKYA
KCE074BCT022

**Comment by Nirumishra** [comment]
[magazine-master (1).zip](https://github.com/Niranjan2054/magazine/files/4677080/magazine-master.1.zip)
Niru Kumari Mishra
740325

**Comment by rohitjoey** [comment]
https://github.com/rohitjoey/project_magazine
Rohit prajapati
074BCT033
