### ISSUE TITLE
CMS: Category, Blog, Advertisement and Follow us

### ISSUE THREAD

**Issue by Niranjan2054** [Niranjan2054/magazine#4]
**Info For Advertisement**
field:

- URL text,
- addType enum('wideadd','simpleadd'),
- Image varchar(50)
Create a form using modal

**Info for Follow Us**
field:
- iconname varchar(20)
- url text,
Create form using modal

Keep the **link of your project repository**, with the final commit message **"Content Management System"** along with your **FULL NAME** and **COLLEGE ROLL NUMBER..**
Dateline: May 30 10:00pm

**Comment by shakyaninja** [comment]
https://github.com/shakyaninja/WebMag
LUJA SHAKYA
KCE074BCT022
(still there is image previewing problem after upload)

**Comment by Niranjan2054** [comment]
> https://github.com/shakyaninja/WebMag
> LUJA SHAKYA
> KCE074BCT022
> (still there is image previewing problem after upload)

**checked**

**Comment by ManandharSudip4** [comment]
https://github.com/ManandharSudip4/-magazine
Sudip Manandhar
(KCE075BCT045)

**Comment by JuJu2181** [comment]
https://github.com/JuJu2181/magazine
Anish Shilpakar
(KCE075BCT008)

**Comment by romanshilpakar** [comment]
https://github.com/romanshilpakar/magazine
Roman Shilpakar
KCE075BCT031

**Comment by Amitduwal11** [comment]
https://github.com/Amitduwal11/magazine
Amit Duwal
KCE075BCT006

**Comment by Manjil-Karki** [comment]
https://github.com/Manjil-Karki/php_web_backend
Manjil Karki
[KCE075BCT019]

**Comment by rravii** [comment]
https://github.com/rravii/magazine/commits/master

Ravi Pandit
(KCE075BCT028)

**Comment by roobeen-b** [comment]
https://github.com/roobeen-b/magazine
Rubin Baidhya
(KCE075BCT034)

**Comment by Nee2z** [comment]
https://github.com/neetuphaiju/magazine
Name : Neetu Phaiju
CRN   : 740324
