### ISSUE TITLE
Final Project Submission

### ISSUE THREAD

**Issue by Niranjan2054** [Niranjan2054/magazine#5]
Submit your final project within **June 12...**
The final commit is "**Final Magazine**" and save the **link of your repository below...**

Everybody need to show their project demonstration...
For demonstration everybody will be contact individually.
Demonstration will be conducted one by one in zoom meeting and need to explain about the projects

**Comment by banmala** [comment]
https://github.com/banmala/magazine
KCE074BCT045
Sunil Banmala

**Comment by shakyaninja** [comment]
https://github.com/shakyaninja/WebMag
KCE074BCT022
Luja Shakya

**Comment by Niranjan2054** [comment]
> https://github.com/banmala/magazine
> KCE074BCT045
> Sunil Banmala

**Comment by rravii** [comment]
https://github.com/rravii/magazine

Ravi Pandit
KCE075BCT028

**Comment by JuJu2181** [comment]
https://github.com/JuJu2181/magazine
Anish Shilpakar
KCE075BCT008

**Comment by ManandharSudip4** [comment]
https://github.com/ManandharSudip4/-magazine
Sudip Manandhar
KCE075BCT045

**Comment by roobeen-b** [comment]
https://github.com/roobeen-b/magazine
Rubin Baidhya
KCE075BCT034
(Added search & newsletter)

**Comment by shakyaninja** [comment]
> https://github.com/shakyaninja/WebMag
> KCE074BCT022
> Luja Shakya

Fixed the issues related to previous final version
https://github.com/shakyaninja/WebMag

**Comment by JuJu2181** [comment]
> https://github.com/JuJu2181/magazine
> Anish Shilpakar
> KCE075BCT008

Added Search and Subscriber 
https://github.com/JuJu2181/magazine

**Comment by Manjil-Karki** [comment]
https://github.com/Manjil-Karki/php-webMag

MANJIL KARKI
KCE075BCT019

**Comment by Manjil-Karki** [comment]
https://github.com/Manjil-Karki/php-webMag

MANJIL KARKI
KCE075BCT019

**Comment by Amitduwal11** [comment]
https://github.com/Amitduwal11/magazinefinal

Amit Duwal
KCE075BCT006

**Comment by rravii** [comment]
https://github.com/rravii/magazine

Fixed the issues related to previous final version
Ravi Pandit
(KCE075BCT028)

**Comment by ManandharSudip4** [comment]
> https://github.com/ManandharSudip4/-magazine
> Sudip Manandhar
> KCE075BCT045

https://github.com/ManandharSudip4/-magazine
Updated Search and Subscribers

**Comment by sahasprajapati** [comment]
https://github.com/B10prajapati/magazine2.0
074bct037
Sahas Prajapati
<a href="http://b10prajapati.epizy.com/">View Site</a>

**Comment by rohitjoey** [comment]
https://github.com/rohitjoey/project_magazine
Rohit Prajapati
074BCT033
[http://magazine-rohit.epizy.com/](url)

**Comment by romanshilpakar** [comment]
https://github.com/romanshilpakar/roomyan
Roman Shilpakar
KCE075BCT031

**Comment by JNPN7** [comment]
https://github.com/JNPN7/magazine
Juhel Phanju
KCE075BCT017
